version: "3.7"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    container_name: db
    image: postgres:11
    logging:
      driver: none
    restart: unless-stopped
    user: postgres
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
      # if you got the error "role admin does not exist" => brew services stop postgresql (a different instance of postgres is already running)

# docker will persist the database under: /var/lib/docker/volumes/upsee_pgdata/_data
volumes:
  pgdata: